### ISSUE TITLE
Hackrf?

### ISSUE THREAD

**Issue by cloatre** [AFITWiSec/killerzee#1]
Hello,

Is-il possible to use this tool with a hackRf or is-it only for a rfcat dongle?

-->when I launch I get this error:
python zwrecon -t eb42dcaf -c UE
WARNING: No route found for IPv6 destination :: (no default route?)
Targeting the broadcast address
Error in resetup():Exception('No Dongle Found.  Please insert a RFCAT dongle.',)

thanks

**Comment by gitjhall** [comment]
@cloatre killerzee only works with an RfCat dongle (highly recommend the YardStickOne). It does not work with any software-defined radio (including the HackRF).
